// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpZHgcAEltJBaOEUSXD78Zp0lDbzpOFjI',
    appId: '1:343333122959:web:68caf0b88133e87ee191fa',
    messagingSenderId: '343333122959',
    projectId: 'chatapp-79cb1',
    authDomain: 'chatapp-79cb1.firebaseapp.com',
    storageBucket: 'chatapp-79cb1.appspot.com',
    measurementId: 'G-9YZQKSMP9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ7j8vuiC5JMCYokeuOakQ5e5B-8IEKxk',
    appId: '1:343333122959:android:c58d7c5e6d5964e9e191fa',
    messagingSenderId: '343333122959',
    projectId: 'chatapp-79cb1',
    storageBucket: 'chatapp-79cb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkZLu-o_jWWuqr_1RfnVKHuHY7kQdP1Kc',
    appId: '1:343333122959:ios:c273a67e8c72cbbee191fa',
    messagingSenderId: '343333122959',
    projectId: 'chatapp-79cb1',
    storageBucket: 'chatapp-79cb1.appspot.com',
    iosClientId: '343333122959-ha8s9hhpcl75jlt5q87mqs3jd84314rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkZLu-o_jWWuqr_1RfnVKHuHY7kQdP1Kc',
    appId: '1:343333122959:ios:c273a67e8c72cbbee191fa',
    messagingSenderId: '343333122959',
    projectId: 'chatapp-79cb1',
    storageBucket: 'chatapp-79cb1.appspot.com',
    iosClientId: '343333122959-ha8s9hhpcl75jlt5q87mqs3jd84314rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
